#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

// Blit
#define BLIT_TEXCOORD_VARYING_LOCATION 0

// Scene
#define SCENE_POSITION_ATTRIB_LOCATION 0
#define SCENE_TEXCOORD_ATTRIB_LOCATION 1
#define SCENE_NORMAL_ATTRIB_LOCATION 2
#define SCENE_TANGENT_ATTRIB_LOCATION 3

#define SCENE_MW_UNIFORM_LOCATION 0
#define SCENE_N_MW_UNIFORM_LOCATION 1
#define SCENE_MVP_UNIFORM_LOCATION 2
#define SCENE_CAMERAPOS_UNIFORM_LOCATION 3
#define SCENE_LIGHTPOS_UNIFORM_LOCATION 4
#define SCENE_AMBIENT_UNIFORM_LOCATION 5
#define SCENE_DIFFUSE_UNIFORM_LOCATION 6
#define SCENE_SPECULAR_UNIFORM_LOCATION 7
#define SCENE_SHININESS_UNIFORM_LOCATION 8
#define SCENE_HAS_DIFFUSE_MAP_UNIFORM_LOCATION 9
#define SCENE_HAS_NORMAL_MAP_UNIFORM_LOCATION 10

#define SCENE_DIFFUSE_MAP_TEXTURE_BINDING 0
#define SCENE_NORMAL_MAP_TEXTURE_BINDING 1

#endif // PREAMBLE_GLSL